apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: my-flask-container
          image: 522161233161.dkr.ecr.eu-west-1.amazonaws.com/my-cloud-native-app:v1
          ports:
            - containerPort: 5001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"
            limits:
              memory: "256Mi"
              ephemeral-storage: "512Mi"